version: '3'
services:

  socketserver:
    container_name: socketserver
    image: bitnami/node:16
    working_dir: /home/cheriefm/backend
    command: sh -c 'yarn install && yarn startprod'
    environment:
      - NODE_ENV=production
      - NODE_PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./backend:/home/cheriefm/backend
    networks:
      - cheriefm-network


  pwa:
    container_name: pwa
    image: bitnami/node:16
    working_dir: /home/cheriefm/front
    command: sh -c 'yarn install && yarn build && yarn start'
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./front:/home/cheriefm/front
    networks:
      - cheriefm-network
    depends_on:
      - socketserver

  apache-cheriefm:
    container_name: apache-cheriefm
    image: bitnami/apache:latest
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./apache/vhosts:/vhosts:ro
    depends_on:
      - socketserver
      - pwa
    networks:
      - cheriefm-network

networks:
  cheriefm-network:
